title: "GandalOps | DevSecOps Portfolio"
description: "My DevSecOps journey, projects, and blogs — by Yogesh Gandal"
baseurl: "" # leave empty
url: "https://gandalops.github.io"

author:
  name: "Yogesh Gandal"
  email: "contact@opsbygandal.dev"
  github: gandalops
  linkedin: yogesh-gandal

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown

