# Site Configuration
title: "Yogesh Gandal DevSecOps Portfolio"
email: contact@opsbygandal.dev
description: >-
  DevSecOps portfolio showcasing secure infrastructure automation, CI/CD pipelines, 
  and cloud security solutions by Yogesh Shankar Gandal.
url: "https://gandalops.github.io"
baseurl: ""
timezone: Europe/Berlin

# Minimal Mistakes Theme
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"
repository: "gandalops/gandalops.github.io"

# Plugins (order matters)
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclusions
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - .github/
  - "*.sh"
  - "*.txt"

# Author Profile
author:
  name: "Yogesh Shankar Gandal"
  avatar: "/assets/images/avatar.png"
  bio: "DevSecOps explorer. From Academia to securing Infra & pipelines."
  location: "Germany"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:contact@opsbygandal.dev"

# Directory Includes
include:
  - _includes/home-content.html
  - _includes/head/custom.html

# Default Front Matter
defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "main"
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      show_featured: false

# Markdown Processor
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Navigation
nav:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects/
  - title: "My Learnings"
    url: /blog/

# Comments
comments:
  provider: "utterances"
  utterances:
    repo: "gandalops/gandalops.github.io"
    issue_term: "pathname"
    theme: "github-light"

# Homepage Customization
home:
  layout: home
  sidebar:
    show_recent: false
    recent_limit: 0
    show_sidebar_ad: false

# Pagination Configuration
pagination:
  enabled: false
  per_page: 8
  permalink: '/page:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Blog Permalinks
collections:
  posts:
    output: true
    permalink: /blog/:year-:month-:day-:title/

# Sitemap Configuration
sitemap:
  changefreq: weekly
  priority: 0.5

# Security Headers (for DevSecOps best practices)
security_headers:
  enabled: true
  csp: |
    default-src 'self';
    script-src 'self' https://utteranc.es https://hits.sh;
    style-src 'self' 'unsafe-inline' https://utteranc.es;
    img-src 'self' https: data:;
    font-src 'self' https://utteranc.es;
    connect-src 'self' https://utteranc.es https://api.utteranc.es;
    frame-src https://utteranc.es
  additional_headers:
    X-XSS-Protection: "1; mode=block"
    X-Content-Type-Options: "nosniff"
    Referrer-Policy: "strict-origin-when-cross-origin"

# GitHub Pages specific
github:
  source:
    branch: main
    exclude:
      - ".github/"
      - "*.sh"
      - "*.txt"