# Site Configuration
title: "Yogesh Gandal DevSecOps Portfolio"
email: contact@opsbygandal.dev
description: >-
  My DevSecOps journey, projects, and blog.
baseurl: ""
url: "https://gandalops.github.io"

# Minimal Mistakes Theme
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"
repository: "gandalops/gandalops.github.io"

# Plugins (order matters)
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclusions
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Author Profile
author:
  name: "Yogesh Shankar Gandal"
  avatar: "/assets/images/avatar.png"
  bio: "DevSecOps explorer. From Academia to securing Infra & pipelines."
  location: "Germany"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:contact@opsbygandal.dev"

# Directory Includes
include:
  - _includes/home-content.html
  - _includes/head/custom.html

# Default Front Matter
defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "main"
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true

# Markdown Processor
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Navigation
nav:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects/
  - title: "Blog"
    url: /blog/

# Comments
comments:
  provider: "utterances"
  utterances:
    repo: "gandalops/gandalops.github.io"
    issue_term: "pathname"
    theme: "github-light"

# Homepage Customization
home:
  layout: home
  sidebar:
    show_recent: false
    recent_limit: 3
    show_sidebar_ad: false

# Pagination Fix
paginate: false
show_excerpts: false

# Blog Permalinks
collections:
  posts:
    output: true
    permalink: /blog/:year-:month-:day-:title/

