# Site Settings
title: "Yogesh Gandal DevSecOps Portfolio"
email: contact@opsbygandal.dev
description: >-
  DevSecOps portfolio showcasing secure infrastructure automation, CI/CD pipelines,
  and cloud security solutions by Yogesh Shankar Gandal.
url: "https://gandalops.github.io"
baseurl: "" # For GitHub Pages project sites, set to "/repository-name"
timezone: Europe/Berlin

# Theme Configuration
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "default"  # Light mode by default
repository: "gandalops/gandalops.github.io"

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-data

# Exclude from Processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - .github/
  - "*.sh"
  - "*.txt"
  - backup-2025-04-20

# Include Additional Files
include:
  - _includes/home-content.html
  - _includes/head/custom.html

# Author Information
author:
  name: "Yogesh Shankar Gandal"
  avatar: "/assets/images/avatar.png"
  bio: "DevSecOps explorer. From Academia to securing Infra & pipelines."
  location: "Germany"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/gandalops"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/yogeshgandal"

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      show_featured: false
      comments: true

# Markdown and Syntax Highlighting
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Navigation
nav:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects/
  - title: "My Learnings"
    url: /blog/

# Comments
comments:
  provider: "utterances"
  utterances:
    repo: "gandalops/gandalops.github.io"
    issue_term: "pathname"
    theme: "github-light"

# Homepage Customization
home:
  layout: home
  sidebar:
    show_recent: false
    recent_limit: 0
    show_sidebar_ad: false

# Pagination
paginate: 8
paginate_path: "/page:num/"

# Permalinks
permalink: /blog/:year-:month-:day-:title/

# Sitemap Settings
sitemap:
  changefreq: weekly
  priority: 0.5

# GitHub Pages Settings
github:
  source:
    branch: main
    exclude:
      - ".github/"
      - "*.sh"
      - "*.txt"

# Google Analytics (GA4)
analytics:
  provider: "google"
  google:
    tracking_id: "G-RNKJP27JVX"
    anonymize_ip: true

# Enable table of contents globally
toc:
  enabled: true
  heading: "Article Contents"
  min_level: 2
  max_level: 3

  sass:
  style: compressed

