
title: "Yogesh Gandal DevSecOps Portfolio"
email: contact@opsbygandal.dev

description: >-
  My DevSecOps journey, projects, and blog.
baseurl: "" # keep it blank for user.github.io repo
url: "https://gandalops.github.io"

theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-remote-theme

remote_theme: "mmistakes/minimal-mistakes"

author:
  name   : GandalOps
  avatar : "/assets/images/avatar.png"
  bio    : "DevSecOps explorer. From Academia to pipelines."
  location: "Germany"

include:
  - _pages

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

markdown: kramdown

nav:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects/
  - title: "Blog"
    url: /blog/
  - title: "Contact"
    url: /contact/


