# Site Configuration
title: "Yogesh Gandal DevSecOps Portfolio"
email: contact@opsbygandal.dev
description: >-
  My DevSecOps journey, projects, and blog.
baseurl: "" # Required for GitHub Pages
url: "https://gandalops.github.io"

# Minimal Mistakes Theme
remote_theme: "mmistakes/minimal-mistakes"


# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-sitemap
  

# Exclusions
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

# Author Profile
author:
  name: "Yogesh Shankar Gandal"
  avatar: "/assets/images/avatar.png"
  bio: "DevSecOps explorer. From Academia to securing Infra & pipelines."
  location: "Germany"

# Directory Includes
include:
  - _includes/home-content.html

  

# Default Front Matter
defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Markdown Processor
markdown: kramdown

# Main Navigation
nav:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects/
  - title: "Blog"
    url: /blog/

comments:
  provider: "utterances"
  utterances:
    repo: "gandalops/gandalops.github.io"
    issue_term: "pathname"